kinematics:
  shoulder:
    x: 0
    y: 0
    z: 0.16253092201988628
    roll: -0
    pitch: 0
    yaw: 2.8565270831365508e-07
  upper_arm:
    x: 0.00015600712793887762
    y: 0
    z: 0
    roll: 1.5703598184116621
    pitch: 0
    yaw: 6.1975338374826853e-06
  forearm:
    x: -0.42520489179175558
    y: 0
    z: 0
    roll: 3.1396940586342068
    pitch: 3.1406556185860341
    yaw: 3.141589667265805
  wrist_1:
    x: -0.39192405312951745
    y: -0.00021003761841280851
    z: 0.13396026461745744
    roll: 0.0015679085652610268
    pitch: 0.0012601364074565551
    yaw: 3.0983711237753793e-06
  wrist_2:
    x: -3.5670680585408752e-05
    y: -0.099786406547352796
    z: 2.1717133926238588e-05
    roll: 1.5705786906024053
    pitch: 0
    yaw: 3.7782394646489197e-06
  wrist_3:
    x: 4.4134750586990308e-05
    y: 0.099481014839154627
    z: 1.5055526110301108e-05
    roll: 1.5709476674906031
    pitch: 3.1415926535897931
    yaw: 3.1415926484010579
  hash: calib_7147691302859851572